apiVersion: v1
data:
  SPRING_DATASOURCE_PASSWORD: V2VsY29tZSMx
  SPRING_DATASOURCE_USERNAME: Y3VyaW9zaXR5
  #SPRING_DATASOURCE_PASSWORD: Welcome#1
  #SPRING_DATASOURCE_USERNAME: championship
kind: Secret
metadata:
  name: consumerms-mysql-db-secret
  namespace: curiosityevents
