apiVersion: v1
data:
  #SPRING_DATASOURCE_USERNAME: c3ByaW5n
  SPRING_DATASOURCE_USERNAME: Y3VyaW9zaXR5
  SPRING_DATASOURCE_PASSWORD: V2VsY29tZSMx
kind: Secret
metadata:
  name: consumerms-mysql-db-secret
  namespace: curiosityevents