apiVersion: v1
kind: Service
metadata:
  name: consumerms-service-clusterip
  namespace: curiosityevents
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8095
  selector:
    app: consumerms